### ISSUE TITLE
[DEMO 4 - Visitor] Website colors

### ISSUE THREAD

**Issue by GigiLoria5** [alessiomason/SE2022-11-HikeTracker#22]
You have done a really well job on the site interfaces. However, I have noticed that there are many different colours used on the various pages, and this can become annoying. The variety of colours can distract attention and make it more difficult to navigate the site. In addition, too many colours can tire the eyes and psyche of users. I would suggest limiting the number of colours used on the site and using more uniform shades to increase the usability and user-friendliness of the interfaces.

**Comment by Luca-Rota** [comment]
Thank you for the advice, I modified the application accordingly, removing the blue color and ineando two different shades of green used. 
Now inside it there are only 4 main colors and each of them is always the same shade and represents a specific element: green for hikes, orange for huts, blue for parking and purple for the user profile. 
The use of these four colors does not damage or confuse the user, but rather helps him to cover more quickly with which element of the application is dealing, without even the use of words.
