### ISSUE TITLE
[DEMO 4 - Local Guide] Not always clear where to find operations 

### ISSUE THREAD

**Issue by GigiLoria5** [alessiomason/SE2022-11-HikeTracker#23]
I have noticed that sometimes it is not always clear where to look for the actions I need. For example, to manage changes in huts, parking lots and hikes, I need to go to my personal profile, but I do not find much correlation in this. This can make it difficult for us local guides to find what we need and can also increase the time needed to complete an action. I would suggest that you consider how to better organise the layout of the site so that it is more intuitive for us local guides to find what we need.

**Comment by salvatoremallemaci** [comment]
As discussed this morning, we decided to keep separate the functionalities of a worker (manage hikes/huts/parking lots for local guides, hike condition for hut-worker, etc.) to the functionalities of the hiker (the real final user) to keep track of the various changes made and to be able to get immediate feedback on how the application will appear to the user. Also in the main page there are the hikes, huts and parking lots created by all the local guides registered on the system, while in the profile page appear only those created by the logged-in one, so the only that he can edit. However, thank you for the advice.
