### ISSUE TITLE
Closed and completed hikes 

### ISSUE THREAD

**Issue by antosams3** [alessiomason/SE2022-11-HikeTracker#24]
As an hiker I find strange the possibility of suspend a hike in progress without being able to resume its execution later on. Moreover, stopped hikes must not be in the list of completed hikes to avoid being misleading. A solution could be just a change of title (from "completed hikes" to "history", for example) or provide stopped ones in a separate list.

**Comment by alessiomason** [comment]
The title has been changed to Tracked hikes, thanks for the suggestion.
